# Exploring crystal space

Our goal is to generate, analyze, and categorize chemical compositions, making it easier to discover interesting and useful materials. This tutorial is based on a publication in [Faraday Discussions](https://pubs.rsc.org/en/content/articlelanding/2024/fd/d4fd00063c).

## 1. Getting started

In this tutorial, we'll:

- Generate binary chemical compositions using the SMACT filter.
- Explore whether these compositions exist in the Materials Project database.
- Categorize the compositions based on whether they pass the SMACT filter and whether they are found in the database.

The final phase will categorize the compositions into four distinct categories based on their properties. The categorization is based on whether a composition is allowed by the SMACT filter (smact_allowed) and whether it is present in the Materials Project database (mp). The categories are as follows:

| smact_allowed | mp   | label      |
|---------------|------|------------|
| yes           | yes  | standard   |
| yes           | no   | missing    |
| no            | yes  | interesting|
| no            | no   | unlikely   |

## 2. Generating compositions

First, we'll create binary chemical compositions using the SMACT filter. The SMACT filter is a smart tool that helps us select compositions based on important chemical rules, such as oxidation states and electronegativity.

To generate these compositions, we'll use a function called [`generate_composition_with_smact`](../../smact/utils/crystal_space/generate_composition_with_smact.py). This function allows us to enumerate all possible binary compositions and filter them based on the SMACT rules. 

### Key parameters:
- `num_elements`: Number of elements in the composition (e.g., 2 for binary).
- `max_stoich`: The maximum ratio of each element (e.g., 8 could mean up to 8 atoms of each element).
- `max_atomic_num`: Maximum atomic number for the elements considered
- `num_processes`: Number of processes to run in parallel to speed up calculations.
- `save_path`: Where to save the generated compositions.

[![Open in Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/WMD-group/SMACT/blob/master/docs/tutorials/crystal_space.ipynb)

In [ ]:
# Install the required packages
try:
    import google.colab

    IN_COLAB = True
except:
    IN_COLAB = False

if IN_COLAB:
    !uv pip install smact[crystal_space] --quiet

In [ ]:
from smact.utils.crystal_space.generate_composition_with_smact import (
    generate_composition_with_smact,
)

In [ ]:
df_smact = generate_composition_with_smact(
    num_elements=2,
    max_stoich=8,
    max_atomic_num=103,
    num_processes=8,
    save_path="data/binary/df_binary_label.pkl",
    oxidation_states_set="smact14",
)

In [ ]:
df_smact

        smact_allowed
Ac2Ag           False
Ac2Ag3          False
Ac2Ag5          False
Ac2Ag7          False
Ac2Al           False
...               ...
ZrZn4           False
ZrZn5           False
ZrZn6           False
ZrZn7           False
ZrZn8           False

[225879 rows x 1 columns]

## 3. Download data from the Materials Project

Next, we download data from the `Materials Project api` using the `download_mp_data` function. This function allows us to download data for a given number of elements and maximum stoichiometry. The data includes the chemical formula, energy, and other properties of the compounds.

[`download_mp_data`](../../smact/utils/crystal_space/download_compounds_with_mp_api.py) function takes in the following parameters:

### Key parameters:
- `mp_api_key`: your Materials Project API key
- `num_elements`: Number of elements in the composition (e.g., 2 for binary).
- `max_stoich`: The maximum ratio of each element (e.g., 8 could mean up to 8 atoms of each element).
- `save_dir`: Where to save the downloaded data

In [ ]:
mp_api_key = ""  # Add your Materials Project API key here

In [ ]:
save_mp_dir = "data/binary/mp_data"

In [ ]:
from smact.utils.crystal_space.download_compounds_with_mp_api import download_mp_data

# download data from MP for binary compounds
docs = download_mp_data(
    mp_api_key=mp_api_key,
    num_elements=2,
    max_stoich=8,
    save_dir=save_mp_dir,
)

  0%|          | 0/22 [00:00<?, ?it/s]

Retrieving SummaryDoc documents:   0%|          | 0/1190 [00:00<?, ?it/s]

  5%|▍         | 1/22 [00:05<02:04,  5.94s/it]

Retrieving SummaryDoc documents:   0%|          | 0/308 [00:00<?, ?it/s]

  9%|▉         | 2/22 [00:08<01:19,  3.97s/it]

Retrieving SummaryDoc documents:   0%|          | 0/98 [00:00<?, ?it/s]

 14%|█▎        | 3/22 [00:10<00:55,  2.91s/it]

Retrieving SummaryDoc documents:   0%|          | 0/616 [00:00<?, ?it/s]

 18%|█▊        | 4/22 [00:12<00:49,  2.74s/it]

Retrieving SummaryDoc documents:   0%|          | 0/486 [00:00<?, ?it/s]

 23%|██▎       | 5/22 [00:14<00:43,  2.56s/it]

Retrieving SummaryDoc documents:   0%|          | 0/132 [00:00<?, ?it/s]

 27%|██▋       | 6/22 [00:17<00:38,  2.42s/it]

Retrieving SummaryDoc documents:   0%|          | 0/93 [00:00<?, ?it/s]

 32%|███▏      | 7/22 [00:18<00:32,  2.15s/it]

Retrieving SummaryDoc documents:   0%|          | 0/175 [00:00<?, ?it/s]

 36%|███▋      | 8/22 [00:20<00:30,  2.20s/it]

Retrieving SummaryDoc documents:   0%|          | 0/151 [00:00<?, ?it/s]

 41%|████      | 9/22 [00:23<00:28,  2.20s/it]

Retrieving SummaryDoc documents:   0%|          | 0/136 [00:00<?, ?it/s]

 45%|████▌     | 10/22 [00:24<00:24,  2.05s/it]

Retrieving SummaryDoc documents:   0%|          | 0/31 [00:00<?, ?it/s]

 50%|█████     | 11/22 [00:26<00:20,  1.86s/it]

Retrieving SummaryDoc documents:   0%|          | 0/71 [00:00<?, ?it/s]

 55%|█████▍    | 12/22 [00:27<00:17,  1.75s/it]

Retrieving SummaryDoc documents:   0%|          | 0/43 [00:00<?, ?it/s]

 59%|█████▉    | 13/22 [00:29<00:14,  1.65s/it]

Retrieving SummaryDoc documents:   0%|          | 0/30 [00:00<?, ?it/s]

 64%|██████▎   | 14/22 [00:30<00:12,  1.56s/it]

Retrieving SummaryDoc documents:   0%|          | 0/3634 [00:00<?, ?it/s]

 68%|██████▊   | 15/22 [00:36<00:19,  2.82s/it]

Retrieving SummaryDoc documents:   0%|          | 0/4755 [00:00<?, ?it/s]

 73%|███████▎  | 16/22 [00:43<00:24,  4.11s/it]

Retrieving SummaryDoc documents:   0%|          | 0/5628 [00:00<?, ?it/s]

 77%|███████▋  | 17/22 [00:51<00:26,  5.25s/it]

Retrieving SummaryDoc documents:   0%|          | 0/687 [00:00<?, ?it/s]

 82%|████████▏ | 18/22 [00:54<00:18,  4.52s/it]

Retrieving SummaryDoc documents:   0%|          | 0/545 [00:00<?, ?it/s]

 86%|████████▋ | 19/22 [00:56<00:11,  3.85s/it]

Retrieving SummaryDoc documents:   0%|          | 0/221 [00:00<?, ?it/s]

 91%|█████████ | 20/22 [00:58<00:06,  3.25s/it]

Retrieving SummaryDoc documents:   0%|          | 0/85 [00:00<?, ?it/s]

 95%|█████████▌| 21/22 [01:00<00:02,  2.91s/it]

Retrieving SummaryDoc documents:   0%|          | 0/37 [00:00<?, ?it/s]

100%|██████████| 22/22 [01:01<00:00,  2.81s/it]

## 4. Categorise compositions

Finally, we categorize the compositions into four labels: standard, missing, interesting, and unlikely.

In [ ]:
from pathlib import Path
import pandas as pd

In [ ]:
mp_data = {p.stem: True for p in Path(save_mp_dir).glob("*.json")}
df_mp = pd.DataFrame.from_dict(mp_data, orient="index", columns=["mp"])

In [ ]:
# make category dataframe
df_category = df_smact.join(df_mp, how="left").fillna(False)

# make label for each category
dict_label = {
    (True, True): "standard",
    (True, False): "missing",
    (False, True): "interesting",
    (False, False): "unlikely",
}
df_category["label"] = df_category.apply(lambda x: dict_label[(x["smact_allowed"], x["mp"])], axis=1)

# count number of each label
print(df_category["label"].value_counts())

# save dataframe
df_category.to_pickle("data/binary/df_binary_category.pkl")

# show df_category
df_category.head()

/tmp/ipykernel_90284/1770874033.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_category = df_smact.join(df_mp, how="left").fillna(False)

label
unlikely       205910
missing          9787
interesting      6505
standard         3677
Name: count, dtype: int64

        smact_allowed     mp     label
Ac2Ag           False  False  unlikely
Ac2Ag3          False  False  unlikely
Ac2Ag5          False  False  unlikely
Ac2Ag7          False  False  unlikely
Ac2Al           False  False  unlikely

# Next steps

move to [`crystal_space_visualisation.ipynb`](crystal_space_visualisation.ipynb) to visualize the data and explore the chemical space.